version: "3.7"

services:
  consul-dc2:
    image: consul:1.8.0-rc1
    command: ["consul","agent","-config-file=/config/consul-dc2.hcl"]
    volumes:
      - "../consul_config:/config"
    ports:
      - 9500:8500
    networks:
      dc2:
        ipv4_address: 10.6.0.2
      wan:
        ipv4_address: 192.169.7.4

  gateway-dc2:
    image: letfn/consul-envoy:v1.8.0-rc1-v0.14.1
    environment:
      CONSUL_HTTP_ADDR: 10.6.0.2:8500
      CONSUL_GRPC_ADDR: 10.6.0.2:8502
    command: [
      "consul",
      "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-address", "10.6.0.5:443",
      "-wan-address", "192.169.7.5:443",
      "--",
      "-l", "debug"]
    networks:
      dc2:
        ipv4_address: 10.6.0.5
      wan:
        ipv4_address: 192.169.7.5

  payments-dc2:
    image: nicholasjackson/fake-service:v0.11.2
    environment:
      LISTEN_ADDR: localhost:9090
      NAME: payments
      MESSAGE: "PAYMENTS V2"
      SERVER_TYPE: "http"
      UPSTREAM_URIS: http://localhost:9091
    networks:
      dc2:
        ipv4_address: 10.6.0.3
  payments-proxy-dc2:
    image: letfn/consul-envoy:v1.8.0-rc1-v0.14.1
    environment:
      CONSUL_HTTP_ADDR: 10.6.0.2:8500
      CONSUL_GRPC_ADDR: 10.6.0.2:8502
      SERVICE_CONFIG: /config/payments_v2.hcl
      CENTRAL_CONFIG: "central_config/payments-defaults.hcl;central_config/payments-resolver.hcl"
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "payments-v2"]
    network_mode: "service:payments-dc2"
